language: node_js
node_js:
- '8'
deploy:
  provider: s3
  access_key_id: AKIAITYEJ7M6VTSDZHLA
  secret_access_key:
    secure: lkrwpeLAv7lZBy/vGPBGjaNVdjJi0J4dl4sV2kKOUKWNRgL1t0jLT7sGij5F1nJqqpmZ/UW3lYHYtV7LfmC2MNXh3jzv0e8QfmV6iJ6kkx16x1NhP/N0shszVPHayIN9aoqikejAPfXUZl+hIRpF/fVs3XGtnZoFoZ5c/Q3iydkMNL+coyY9INMDmJ5cWYVSAHUVv8ta+p9TRq9RMPfe0OgFnzURkIpIvK5fsszaHnRJ5o1p+awUxAhNE2GN7yuA38rMYEZTUDrah3w604i0GjRJNSOw2XRkTkSpOxYIW4cSjShr/Ko+e0WooiKjZR+oOKS+qNLcS1e3r532YaS3d3G3aq3buRCM1bzLnWk+cgpXwu8cYhc3b8Luk1q2zcjwkHVMXYgsD33AK1genU/zWBWElGIeeGmWK6ZwgopmYipfyRJSzmoKKnPAJHL7O/h1fQi0v1W9wi/9jBOvbWZFpEloIA4vC7CajYFEDsygJ7u8pt7isihE8Dbf0GxoKgvfKMBrLEemiMrOzJ+lic/Se5qXthPXuYGm0p+kg5dCG7sLwxK3HjGye9f4032K1BhXRd1krU+raubuCaGO/WURboesD9/1JzT6nlbAq9XyPZxV4OdAdIhgm+7kLi3lHsy6m223N2Tsc+gjzGKrL8joZPrSwcoERyNSeGr0skZo0S8=
  bucket: xxtechconfspeakers.org
  local-dir: dist
  upload-dir: preview
  region: ap-southeast-2
  skip_cleanup: true
  on:
    repo: andeemarks/xxtechconfspeakers
